"""Serialize a Document as Hyprland Lua config (v0.55.0+).

This is a one-way emitter: it walks the document's KeyValueLine nodes and
produces an equivalent Lua config built around the ``hl.*`` API. Comments,
blank lines, variables, and conditionals from the source Hyprlang document
are *not* preserved — Lua and Hyprlang are structurally different enough that
faithful round-trip would require a richer Lua AST.

Phase 1 scope:
- ``section:key = value`` → merged into a single ``hl.config({...})`` call,
  with nested tables for both colon (``section:sub:key``) and dot
  (``section:col.inactive_border``) separators.
- ``env``, ``monitor``, ``bezier``, ``animation`` → dedicated ``hl.*`` calls.
- Values coerce to Lua bool/int/float when the string parses unambiguously;
  everything else is quoted as a string.

Phase 2+ keywords (``bind``, ``windowrule``, ``layerrule``, ``workspace``,
``gesture``, ``device``, ``exec``…) are intentionally skipped here and
flagged in the output as a TODO comment so users know what wasn't migrated.
"""

import re
from typing import Any

from hyprland_config._model import Assignment, Document, Keyword

_HEADER = "-- Generated by hyprland-config — Hyprland Lua config (v0.55.0+)\n\n"
_INDENT = "    "

_INT_RE = re.compile(r"^-?\d+$")
_FLOAT_RE = re.compile(r"^-?\d+\.\d+$")
_IDENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

# Lua reserved words can't be used as bare-key identifiers in table literals.
_LUA_KEYWORDS = frozenset(
    {
        "and",
        "break",
        "do",
        "else",
        "elseif",
        "end",
        "false",
        "for",
        "function",
        "goto",
        "if",
        "in",
        "local",
        "nil",
        "not",
        "or",
        "repeat",
        "return",
        "then",
        "true",
        "until",
        "while",
    }
)

# Phase-1 keyword handlers; everything else is skipped with a TODO marker.
_HANDLED_KEYWORDS = frozenset({"env", "monitor", "bezier", "animation"})


def serialize_lua(doc: Document) -> str:
    """Render *doc* as a Lua config string.

    Walks the document non-recursively (single-file emit; callers driving
    multi-file output should iterate sub-documents themselves). Returns a
    string ending in a newline; an empty document returns just the header.
    """
    config_tree: dict[str, Any] = {}
    extras: list[str] = []
    skipped: list[str] = []

    for line in doc.lines:
        if isinstance(line, Assignment):
            _set_nested(config_tree, _split_key(line.full_key), _coerce_value(line.value))
        elif isinstance(line, Keyword):
            if line.key in _HANDLED_KEYWORDS:
                extras.append(_emit_keyword(line.key, line.value))
            else:
                skipped.append(f"{line.key} = {line.value}")

    parts: list[str] = [_HEADER]

    if config_tree:
        parts.append("hl.config(")
        parts.append(_format_table(config_tree, indent=0))
        parts.append(")\n")

    if extras:
        if config_tree:
            parts.append("\n")
        parts.extend(call + "\n" for call in extras)

    if skipped:
        if config_tree or extras:
            parts.append("\n")
        parts.append("-- TODO: the following entries need manual conversion to Lua:\n")
        parts.extend(f"--   {entry}\n" for entry in skipped)

    return "".join(parts)


# ---------------------------------------------------------------------------
# Key handling
# ---------------------------------------------------------------------------


def _split_key(full_key: str) -> list[str]:
    """Split a full key like ``general:col.inactive_border`` into nesting parts.

    Both ``:`` (Hyprlang section separator) and ``.`` (sub-prefix convention,
    e.g. ``col.inactive_border``) become nesting boundaries in the Lua table.
    Empty parts from leading/trailing separators are dropped.
    """
    return [part for part in re.split(r"[:.]", full_key) if part]


def _set_nested(tree: dict[str, Any], path: list[str], value: Any) -> None:
    """Set ``tree[p1][p2]...[pN] = value``, creating intermediate dicts.

    If an intermediate node was previously bound to a non-dict value (e.g.
    ``general:gaps_in`` set as an int then ``general:gaps_in:override`` tried
    to nest under it), the non-dict value is replaced so we still produce
    valid Lua rather than crashing on malformed input.
    """
    if not path:
        return
    *parents, leaf = path
    node = tree
    for part in parents:
        existing = node.get(part)
        if not isinstance(existing, dict):
            node[part] = {}
        node = node[part]
    node[leaf] = value


# ---------------------------------------------------------------------------
# Value coercion + formatting
# ---------------------------------------------------------------------------


def _coerce_value(s: str) -> Any:
    """Best-effort coerce a Hyprlang value string to a Lua-ready Python value.

    Without schema awareness we can only key off the literal shape, so:
    - exact integer/float literals become numbers,
    - the case-insensitive words ``true``/``false`` become booleans,
    - everything else (colors, gradients, vec2, paths, free text) stays a
      string and gets quoted on emit.
    """
    stripped = s.strip()
    if _INT_RE.match(stripped):
        return int(stripped)
    if _FLOAT_RE.match(stripped):
        return float(stripped)
    if stripped.lower() == "true":
        return True
    if stripped.lower() == "false":
        return False
    return s


def _quote_string(s: str) -> str:
    """Quote *s* as a Lua double-quoted string literal."""
    escaped = (
        s.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'


def _format_key(k: str) -> str:
    """Render a table key — bare identifier when possible, ``[\"…\"]`` otherwise."""
    if _IDENT_RE.match(k) and k not in _LUA_KEYWORDS:
        return k
    return f"[{_quote_string(k)}]"


def _format_value(value: Any, indent: int) -> str:
    """Render *value* as Lua source at the given indentation level."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        text = format(value, ".15g")
        if "." not in text and "e" not in text and "n" not in text:
            text += ".0"
        return text
    if isinstance(value, str):
        return _quote_string(value)
    if isinstance(value, dict):
        return _format_table(value, indent)
    raise TypeError(f"Cannot format Lua value of type {type(value).__name__}")


def _format_table(table: dict[str, Any], indent: int) -> str:
    """Render a dict as a multi-line Lua table literal."""
    if not table:
        return "{}"
    inner = _INDENT * (indent + 1)
    outer = _INDENT * indent
    lines = ["{"]
    for k, v in table.items():
        lines.append(f"{inner}{_format_key(k)} = {_format_value(v, indent + 1)},")
    lines.append(f"{outer}}}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Special-keyword emitters
# ---------------------------------------------------------------------------


def _split_csv(args: str) -> list[str]:
    """Split Hyprlang comma-separated arguments, trimming surrounding whitespace."""
    return [part.strip() for part in args.split(",")]


def _emit_keyword(name: str, args: str) -> str:
    """Dispatch to the right emitter for a Phase-1 keyword."""
    if name == "env":
        return _emit_env(args)
    if name == "monitor":
        return _emit_monitor(args)
    if name == "bezier":
        return _emit_bezier(args)
    if name == "animation":
        return _emit_animation(args)
    raise AssertionError(f"unhandled keyword {name!r}")


def _emit_env(args: str) -> str:
    """``env = NAME, VALUE`` → ``hl.env("NAME", "VALUE")``."""
    parts = _split_csv(args)
    name = parts[0] if parts else ""
    value = parts[1] if len(parts) >= 2 else ""
    return f"hl.env({_quote_string(name)}, {_quote_string(value)})"


def _emit_monitor(args: str) -> str:
    """``monitor = OUTPUT, MODE, POSITION, SCALE`` → ``hl.monitor({...})``.

    Trailing arguments past the four positional ones aren't decoded here —
    they survive parsing only when extras like ``transform, …`` are present
    and we'd need monitor-rule knowledge to map them. For Phase 1 we emit
    just the four positional fields; users with extras get a TODO marker.
    """
    parts = _split_csv(args)
    table: dict[str, Any] = {}
    if parts and parts[0]:
        table["output"] = parts[0]
    if len(parts) >= 2:
        table["mode"] = parts[1]
    if len(parts) >= 3:
        table["position"] = parts[2]
    if len(parts) >= 4:
        table["scale"] = _coerce_value(parts[3])
    if len(parts) > 4:
        table["__extras"] = ", ".join(parts[4:])
    return f"hl.monitor({_format_table(table, indent=0)})"


def _emit_bezier(args: str) -> str:
    """``bezier = NAME, x0, y0, x1, y1`` → ``hl.curve(NAME, {type="bezier", …})``."""
    parts = _split_csv(args)
    if len(parts) < 5:
        return f"-- malformed bezier: {args}"
    name = parts[0]
    p1x, p1y = _coerce_value(parts[1]), _coerce_value(parts[2])
    p2x, p2y = _coerce_value(parts[3]), _coerce_value(parts[4])
    point1 = f"{{{_format_value(p1x, 0)}, {_format_value(p1y, 0)}}}"
    point2 = f"{{{_format_value(p2x, 0)}, {_format_value(p2y, 0)}}}"
    return (
        f'hl.curve({_quote_string(name)}, {{ type = "bezier", points = {{ {point1}, {point2} }} }})'
    )


# Hyprlang's animation "enabled" flag accepts a few synonyms; treat them all
# as truthy so the emitted Lua boolean matches user intent.
_ANIMATION_TRUE = frozenset({"1", "true", "yes", "on"})


def _emit_animation(args: str) -> str:
    """``animation = NAME, ONOFF, SPEED, CURVE [, STYLE]`` → ``hl.animation({…})``."""
    parts = _split_csv(args)
    if not parts:
        return f"-- malformed animation: {args}"
    table: dict[str, Any] = {"leaf": parts[0]}
    if len(parts) >= 2:
        table["enabled"] = parts[1].strip().lower() in _ANIMATION_TRUE
    if len(parts) >= 3:
        table["speed"] = _coerce_value(parts[2])
    if len(parts) >= 4 and parts[3]:
        table["bezier"] = parts[3]
    if len(parts) >= 5 and parts[4]:
        table["style"] = parts[4]
    return f"hl.animation({_format_table(table, indent=0)})"
