"""Tests for the Lua emitter."""

from hyprland_config import Document, parse_string, serialize_lua

HEADER = "-- Generated by hyprland-config — Hyprland Lua config (v0.55.0+)\n\n"


class TestEmptyDocument:
    def test_empty_doc_returns_header_only(self) -> None:
        assert serialize_lua(Document()) == HEADER

    def test_parsed_empty_string(self) -> None:
        assert parse_string("").serialize_lua() == HEADER

    def test_only_comments_returns_header_only(self) -> None:
        # Comments aren't preserved in the Lua output.
        assert parse_string("# just a comment\n").serialize_lua() == HEADER


class TestCategoryAssignments:
    def test_single_assignment(self) -> None:
        out = parse_string("general:gaps_in = 5\n").serialize_lua()
        assert "hl.config(" in out
        assert "general = {" in out
        assert "gaps_in = 5," in out

    def test_multiple_in_same_section(self) -> None:
        out = parse_string("general:gaps_in = 5\ngeneral:gaps_out = 20\n").serialize_lua()
        assert out.count("hl.config(") == 1
        assert "gaps_in = 5," in out
        assert "gaps_out = 20," in out

    def test_section_block_syntax(self) -> None:
        out = parse_string("general {\n    gaps_in = 5\n    gaps_out = 20\n}\n").serialize_lua()
        assert "general = {" in out
        assert "gaps_in = 5," in out
        assert "gaps_out = 20," in out

    def test_nested_colon_path(self) -> None:
        out = parse_string("decoration:blur:size = 3\n").serialize_lua()
        assert "decoration = {" in out
        assert "blur = {" in out
        assert "size = 3," in out

    def test_dotted_key_becomes_subtable(self) -> None:
        # `col.inactive_border` is Hyprlang's prefix convention and maps to a
        # nested Lua table.
        out = parse_string("general:col.inactive_border = rgba(595959aa)\n").serialize_lua()
        assert "col = {" in out
        assert 'inactive_border = "rgba(595959aa)",' in out

    def test_mixed_colon_and_dot(self) -> None:
        out = parse_string("group:groupbar:col.active = 0xff112233\n").serialize_lua()
        assert "group = {" in out
        assert "groupbar = {" in out
        assert "col = {" in out
        assert 'active = "0xff112233",' in out

    def test_last_value_wins(self) -> None:
        out = parse_string("general:gaps_in = 5\ngeneral:gaps_in = 10\n").serialize_lua()
        assert "gaps_in = 10," in out
        assert "gaps_in = 5," not in out


class TestValueCoercion:
    def test_int_emitted_as_number(self) -> None:
        assert "gaps_in = 5," in parse_string("general:gaps_in = 5\n").serialize_lua()

    def test_negative_int(self) -> None:
        assert "force_default_wallpaper = -1," in (
            parse_string("misc:force_default_wallpaper = -1\n").serialize_lua()
        )

    def test_float_emitted_as_number(self) -> None:
        out = parse_string("decoration:active_opacity = 0.9\n").serialize_lua()
        assert "active_opacity = 0.9," in out

    def test_bool_true(self) -> None:
        assert "enabled = true," in parse_string("decoration:blur:enabled = true\n").serialize_lua()

    def test_bool_false(self) -> None:
        out = parse_string("misc:disable_hyprland_logo = false\n").serialize_lua()
        assert "disable_hyprland_logo = false," in out

    def test_bool_case_insensitive(self) -> None:
        # Hyprlang accepts True/TRUE/etc.; we coerce them all to lowercase Lua.
        assert "x = true," in parse_string("general:x = True\n").serialize_lua()
        assert "x = false," in parse_string("general:x = FALSE\n").serialize_lua()

    def test_string_value_quoted(self) -> None:
        assert 'kb_layout = "us",' in parse_string("input:kb_layout = us\n").serialize_lua()

    def test_string_with_special_chars_escaped(self) -> None:
        # Hyprlang doesn't really emit these in defaults, but the emitter
        # must still handle them safely if set programmatically.
        doc = parse_string("input:kb_layout = us\n")
        node = doc.find("input:kb_layout")
        assert node is not None
        node.value = 'a"b\\c'
        out = doc.serialize_lua()
        assert r'kb_layout = "a\"b\\c",' in out

    def test_color_kept_as_string(self) -> None:
        out = parse_string("general:col.active_border = rgba(33ccffee)\n").serialize_lua()
        assert 'active_border = "rgba(33ccffee)",' in out


class TestKeyFormatting:
    def test_lua_reserved_word_as_key_gets_bracketed(self) -> None:
        # Theoretical case — unlikely in real configs but the emitter must
        # not produce invalid Lua identifiers.
        doc = parse_string("foo:end = 1\n")
        out = doc.serialize_lua()
        assert '["end"] = 1,' in out

    def test_non_identifier_key_gets_bracketed(self) -> None:
        doc = parse_string("foo:weird-key = 1\n")
        out = doc.serialize_lua()
        assert '["weird-key"] = 1,' in out


class TestEnvKeyword:
    def test_env_emits_hl_env(self) -> None:
        out = parse_string("env = XCURSOR_SIZE, 24\n").serialize_lua()
        assert 'hl.env("XCURSOR_SIZE", "24")' in out

    def test_env_with_path_value(self) -> None:
        out = parse_string("env = GTK_THEME, Adwaita-dark\n").serialize_lua()
        assert 'hl.env("GTK_THEME", "Adwaita-dark")' in out

    def test_multiple_env_lines_kept_separate(self) -> None:
        out = parse_string("env = A, 1\nenv = B, 2\n").serialize_lua()
        assert 'hl.env("A", "1")' in out
        assert 'hl.env("B", "2")' in out


class TestMonitorKeyword:
    def test_monitor_full_form(self) -> None:
        out = parse_string("monitor = DP-1, 2560x1440@144, 0x0, 1\n").serialize_lua()
        assert "hl.monitor({" in out
        assert 'output = "DP-1",' in out
        assert 'mode = "2560x1440@144",' in out
        assert 'position = "0x0",' in out
        assert "scale = 1," in out

    def test_monitor_with_float_scale(self) -> None:
        out = parse_string("monitor = DP-1, preferred, auto, 1.5\n").serialize_lua()
        assert "scale = 1.5," in out

    def test_monitor_with_extras_preserved_verbatim(self) -> None:
        # We don't decode transform/mirror/bitdepth in Phase 1; surface them
        # so users see them in the output but know they need attention.
        out = parse_string("monitor = DP-1, preferred, auto, 1, transform, 1\n").serialize_lua()
        assert "__extras" in out


class TestBezierKeyword:
    def test_bezier_emits_hl_curve(self) -> None:
        out = parse_string("bezier = easeOut, 0.05, 0.9, 0.1, 1.0\n").serialize_lua()
        assert 'hl.curve("easeOut"' in out
        assert 'type = "bezier"' in out
        assert "{0.05, 0.9}" in out
        assert "{0.1, 1.0}" in out

    def test_bezier_with_integer_points(self) -> None:
        out = parse_string("bezier = linear, 0, 0, 1, 1\n").serialize_lua()
        assert "{0, 0}" in out
        assert "{1, 1}" in out


class TestAnimationKeyword:
    def test_animation_full_form(self) -> None:
        out = parse_string("animation = windows, 1, 7, easeOut, slide\n").serialize_lua()
        assert "hl.animation({" in out
        assert 'leaf = "windows",' in out
        assert "enabled = true," in out
        assert "speed = 7," in out
        assert 'bezier = "easeOut",' in out
        assert 'style = "slide",' in out

    def test_animation_disabled(self) -> None:
        out = parse_string("animation = windows, 0, 7, default\n").serialize_lua()
        assert "enabled = false," in out

    def test_animation_synonyms_for_enabled(self) -> None:
        # Hyprlang accepts yes/on as truthy synonyms.
        out = parse_string("animation = w, yes, 1, default\n").serialize_lua()
        assert "enabled = true," in out

    def test_animation_without_style(self) -> None:
        out = parse_string("animation = layers, 1, 4, easeOut\n").serialize_lua()
        assert "style" not in out


class TestUnsupportedKeywords:
    def test_bind_goes_to_todo_section(self) -> None:
        out = parse_string("bind = SUPER, Q, killactive,\n").serialize_lua()
        assert "hl.bind" not in out
        assert "-- TODO" in out
        assert "bind = SUPER, Q, killactive," in out

    def test_windowrule_in_todo(self) -> None:
        out = parse_string("windowrule = float, class:.*\n").serialize_lua()
        assert "-- TODO" in out
        assert "windowrule = float, class:.*" in out

    def test_multiple_unsupported_listed_in_one_todo_block(self) -> None:
        out = parse_string("bind = SUPER, Q,\nbind = SUPER, W,\nexec = waybar\n").serialize_lua()
        assert out.count("-- TODO") == 1
        assert "bind = SUPER, Q," in out
        assert "bind = SUPER, W," in out
        assert "exec = waybar" in out


class TestStructure:
    def test_only_assignments_no_extras_block(self) -> None:
        out = parse_string("general:gaps_in = 5\n").serialize_lua()
        assert "hl.config(" in out
        assert "hl.env" not in out

    def test_only_keywords_no_config_block(self) -> None:
        out = parse_string("env = X, 1\n").serialize_lua()
        assert "hl.config(" not in out
        assert 'hl.env("X", "1")' in out

    def test_assignments_then_extras_then_todo(self) -> None:
        out = parse_string("general:gaps_in = 5\nenv = X, 1\nbind = SUPER, Q,\n").serialize_lua()
        # The three blocks appear in this order.
        config_idx = out.index("hl.config(")
        env_idx = out.index("hl.env")
        todo_idx = out.index("-- TODO")
        assert config_idx < env_idx < todo_idx


class TestCleanFileShape:
    def test_output_ends_with_newline(self) -> None:
        assert parse_string("general:gaps_in = 5\n").serialize_lua().endswith("\n")

    def test_header_present(self) -> None:
        assert parse_string("general:gaps_in = 5\n").serialize_lua().startswith(HEADER)

    def test_serialize_lua_is_module_level_function(self) -> None:
        # Both call paths should produce the same output.
        doc = parse_string("general:gaps_in = 5\n")
        assert serialize_lua(doc) == doc.serialize_lua()
